### PR TITLE
linux: Add CoreSight support Kconfigs

### PR DESCRIPTION
**Pull request by nareshkamboju**
Adding CoreSight support Kconfigs to LKFT builds.
Following configs are suggested by Leo and Basil,

	#Coresight driver flags
	CONFIG_CORESIGHT=y
	CONFIG_CORESIGHT_LINKS_AND_SINKS=y
	CONFIG_CORESIGHT_LINK_AND_SINK_TMC=y
	CONFIG_CORESIGHT_CATU=y
	CONFIG_CORESIGHT_SOURCE_ETM4X=y
	CONFIG_CORESIGHT_SINK_TPIU=y

	#Perf support
	CONFIG_PERF_EVENTS=y

	#SCMI support
	CONFIG_ARM_SCMI_PROTOCOL=y
	CONFIG_SENSORS_ARM_SCMI=y
	CONFIG_COMMON_CLK_SCMI=y
	CONFIG_ARM_SCMI_CPUFREQ=y

Ref:
Introduce CoreSight support to LKFT
https://projects.linaro.org/browse/LKQ-268

Signed-off-by: Naresh Kamboju <naresh.kamboju@linaro.org>

### CODE REVIEW

**Review by bhcopeland — APPROVED** [review]

**Comment by roxell** [comment]
LGTM

**Comment by mrchapp** [comment]
+1

**Review by mrchapp — CHANGES_REQUESTED** [review]
While we're waiting for the RC's, can you add a space between hash and comment? Like the other comments in the file.

**Comment by nareshkamboju** [comment]
@mrchapp Thanks for review.
Your comments have been addressed now.

**Review by mrchapp — APPROVED** [review]

**Pull request merged**
