### PR TITLE
linux: Adding config MEDIA_TEST_SUPPORT for V4L2 testing

### PR DESCRIPTION
**Pull request by nareshkamboju**
With the new changes in media drives we have to enable
CONFIG_MEDIA_TEST_SUPPORT=y as pre requirement for V4L2 testing

This config tested on i386
https://lkft.validation.linaro.org/results/1482258

Signed-off-by: Naresh Kamboju <naresh.kamboju@linaro.org>

### CODE REVIEW

**Comment by nareshkamboju** [comment]
Testing on Juno and x86
Allow sometime to validate.

**Comment by nareshkamboju** [comment]
Tested on arm64 and x86_64 and V4L2 test pass.
https://lkft.validation.linaro.org/results/1482424
https://lkft.validation.linaro.org/results/1482422


@mrchapp  Please review.

**Review by mrchapp — APPROVED** [review]

**Comment by mrchapp** [comment]
Can you change the commit subject? Start with "linux: ".

**Comment by nareshkamboju** [comment]
> Can you change the commit subject? Start with "linux: ".

@mrchapp Changed to "linux:"
Thanks for the review.

**Pull request merged**
