### PR TITLE
kselftests: mainline, update to latest minor release

### PR DESCRIPTION
**Pull request by roxell**
Signed-off-by: Anders Roxell <anders.roxell@linaro.org>

### CODE REVIEW

**Comment by danrue** [comment]
Can we just go straight to the latest 5.2?

**Comment by mrchapp** [comment]
@nareshkamboju, I too would like to move forward to 5.2.11.

**Comment by roxell** [comment]
We can, but we can also get this in now (for tomorrows build) and do 5.2.11 will take a bit longer with testing I assume or will the testing be equally but twice as much if we do both?

**Comment by mrchapp** [comment]
This one can go in directly, no need to retest the entire thing. I'll merge it, because it's a good backup in case we can't get 5.2.x by tomorrow.

**Pull request merged**
