### PR TITLE
linux: lkft.config: enable libgipod

### PR DESCRIPTION
**Pull request by roxell**
When running libgpiod tests the following warning shows up:

[32m[INFO]  [0mchecking the linux kernel version
[32m[INFO]  [0mkernel release is v5.15.0 - ok to run tests
[32m[INFO]  [0musing gpio-tools from '/usr/bin'
[31m[FATAL] [0merror checking the availability of gpio-mockup: No such file or directory
[32m[INFO]  [0mcleaning up

Enable needed fragments.

Signed-off-by: Anders Roxell <anders.roxell@linaro.org>

### CODE REVIEW

**Review by mrchapp — APPROVED** [review]

**Comment by roxell** [comment]
hmm not sure about this

**Comment by roxell** [comment]
https://builds.tuxbuild.com/202lSAj3DjVKdG19n4JHRUbhXbm/

**Comment by roxell** [comment]
closing this one...

**Comment by mrchapp** [comment]
> https://builds.tuxbuild.com/202lSAj3DjVKdG19n4JHRUbhXbm/

What does this explain?

**Pull request closed without merging**
